require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CampaignItemsController do

  # This should return the minimal set of attributes required to create a valid
  # CampaignItem. As you add validations to CampaignItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "duration_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CampaignItemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all campaign_items as @campaign_items" do
      campaign_item = CampaignItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:campaign_items).should eq([campaign_item])
    end
  end

  describe "GET show" do
    it "assigns the requested campaign_item as @campaign_item" do
      campaign_item = CampaignItem.create! valid_attributes
      get :show, {:id => campaign_item.to_param}, valid_session
      assigns(:campaign_item).should eq(campaign_item)
    end
  end

  describe "GET new" do
    it "assigns a new campaign_item as @campaign_item" do
      get :new, {}, valid_session
      assigns(:campaign_item).should be_a_new(CampaignItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested campaign_item as @campaign_item" do
      campaign_item = CampaignItem.create! valid_attributes
      get :edit, {:id => campaign_item.to_param}, valid_session
      assigns(:campaign_item).should eq(campaign_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CampaignItem" do
        expect {
          post :create, {:campaign_item => valid_attributes}, valid_session
        }.to change(CampaignItem, :count).by(1)
      end

      it "assigns a newly created campaign_item as @campaign_item" do
        post :create, {:campaign_item => valid_attributes}, valid_session
        assigns(:campaign_item).should be_a(CampaignItem)
        assigns(:campaign_item).should be_persisted
      end

      it "redirects to the created campaign_item" do
        post :create, {:campaign_item => valid_attributes}, valid_session
        response.should redirect_to(CampaignItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved campaign_item as @campaign_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        CampaignItem.any_instance.stub(:save).and_return(false)
        post :create, {:campaign_item => { "duration_id" => "invalid value" }}, valid_session
        assigns(:campaign_item).should be_a_new(CampaignItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CampaignItem.any_instance.stub(:save).and_return(false)
        post :create, {:campaign_item => { "duration_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested campaign_item" do
        campaign_item = CampaignItem.create! valid_attributes
        # Assuming there are no other campaign_items in the database, this
        # specifies that the CampaignItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CampaignItem.any_instance.should_receive(:update).with({ "duration_id" => "1" })
        put :update, {:id => campaign_item.to_param, :campaign_item => { "duration_id" => "1" }}, valid_session
      end

      it "assigns the requested campaign_item as @campaign_item" do
        campaign_item = CampaignItem.create! valid_attributes
        put :update, {:id => campaign_item.to_param, :campaign_item => valid_attributes}, valid_session
        assigns(:campaign_item).should eq(campaign_item)
      end

      it "redirects to the campaign_item" do
        campaign_item = CampaignItem.create! valid_attributes
        put :update, {:id => campaign_item.to_param, :campaign_item => valid_attributes}, valid_session
        response.should redirect_to(campaign_item)
      end
    end

    describe "with invalid params" do
      it "assigns the campaign_item as @campaign_item" do
        campaign_item = CampaignItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CampaignItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => campaign_item.to_param, :campaign_item => { "duration_id" => "invalid value" }}, valid_session
        assigns(:campaign_item).should eq(campaign_item)
      end

      it "re-renders the 'edit' template" do
        campaign_item = CampaignItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CampaignItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => campaign_item.to_param, :campaign_item => { "duration_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested campaign_item" do
      campaign_item = CampaignItem.create! valid_attributes
      expect {
        delete :destroy, {:id => campaign_item.to_param}, valid_session
      }.to change(CampaignItem, :count).by(-1)
    end

    it "redirects to the campaign_items list" do
      campaign_item = CampaignItem.create! valid_attributes
      delete :destroy, {:id => campaign_item.to_param}, valid_session
      response.should redirect_to(campaign_items_url)
    end
  end

end
